// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Reflection;
using Microsoft.ML.Data;

namespace Zzb_ML_GobangML.Model
{
    public class ModelInput
    {
        [ColumnName("GobangId"), LoadColumn(0)]
        public string GobangId { get; set; }


        [ColumnName("CreateTime"), LoadColumn(1)]
        public string CreateTime { get; set; }


        [ColumnName("UpdateTime"), LoadColumn(2)]
        public string UpdateTime { get; set; }


        [ColumnName("IsEnable"), LoadColumn(3)]
        public bool IsEnable { get; set; }


        [ColumnName("Point1"), LoadColumn(4)]
        public float Point1 { get; set; }


        [ColumnName("Point2"), LoadColumn(5)]
        public float Point2 { get; set; }


        [ColumnName("Point3"), LoadColumn(6)]
        public float Point3 { get; set; }


        [ColumnName("Point4"), LoadColumn(7)]
        public float Point4 { get; set; }


        [ColumnName("Point5"), LoadColumn(8)]
        public float Point5 { get; set; }


        [ColumnName("Point6"), LoadColumn(9)]
        public float Point6 { get; set; }


        [ColumnName("Point7"), LoadColumn(10)]
        public float Point7 { get; set; }


        [ColumnName("Point8"), LoadColumn(11)]
        public float Point8 { get; set; }


        [ColumnName("Point9"), LoadColumn(12)]
        public float Point9 { get; set; }


        [ColumnName("Point10"), LoadColumn(13)]
        public float Point10 { get; set; }


        [ColumnName("Point11"), LoadColumn(14)]
        public float Point11 { get; set; }


        [ColumnName("Point12"), LoadColumn(15)]
        public float Point12 { get; set; }


        [ColumnName("Point13"), LoadColumn(16)]
        public float Point13 { get; set; }


        [ColumnName("Point14"), LoadColumn(17)]
        public float Point14 { get; set; }


        [ColumnName("Point15"), LoadColumn(18)]
        public float Point15 { get; set; }


        [ColumnName("Point16"), LoadColumn(19)]
        public float Point16 { get; set; }


        [ColumnName("Point17"), LoadColumn(20)]
        public float Point17 { get; set; }


        [ColumnName("Point18"), LoadColumn(21)]
        public float Point18 { get; set; }


        [ColumnName("Point19"), LoadColumn(22)]
        public float Point19 { get; set; }


        [ColumnName("Point20"), LoadColumn(23)]
        public float Point20 { get; set; }


        [ColumnName("Point21"), LoadColumn(24)]
        public float Point21 { get; set; }


        [ColumnName("Point22"), LoadColumn(25)]
        public float Point22 { get; set; }


        [ColumnName("Point23"), LoadColumn(26)]
        public float Point23 { get; set; }


        [ColumnName("Point24"), LoadColumn(27)]
        public float Point24 { get; set; }


        [ColumnName("Point25"), LoadColumn(28)]
        public float Point25 { get; set; }


        [ColumnName("Point26"), LoadColumn(29)]
        public float Point26 { get; set; }


        [ColumnName("Point27"), LoadColumn(30)]
        public float Point27 { get; set; }


        [ColumnName("Point28"), LoadColumn(31)]
        public float Point28 { get; set; }


        [ColumnName("Point29"), LoadColumn(32)]
        public float Point29 { get; set; }


        [ColumnName("Point30"), LoadColumn(33)]
        public float Point30 { get; set; }


        [ColumnName("Point31"), LoadColumn(34)]
        public float Point31 { get; set; }


        [ColumnName("Point32"), LoadColumn(35)]
        public float Point32 { get; set; }


        [ColumnName("Point33"), LoadColumn(36)]
        public float Point33 { get; set; }


        [ColumnName("Point34"), LoadColumn(37)]
        public float Point34 { get; set; }


        [ColumnName("Point35"), LoadColumn(38)]
        public float Point35 { get; set; }


        [ColumnName("Point36"), LoadColumn(39)]
        public float Point36 { get; set; }


        [ColumnName("Point37"), LoadColumn(40)]
        public float Point37 { get; set; }


        [ColumnName("Point38"), LoadColumn(41)]
        public float Point38 { get; set; }


        [ColumnName("Point39"), LoadColumn(42)]
        public float Point39 { get; set; }


        [ColumnName("Point40"), LoadColumn(43)]
        public float Point40 { get; set; }


        [ColumnName("Point41"), LoadColumn(44)]
        public float Point41 { get; set; }


        [ColumnName("Point42"), LoadColumn(45)]
        public float Point42 { get; set; }


        [ColumnName("Point43"), LoadColumn(46)]
        public float Point43 { get; set; }


        [ColumnName("Point44"), LoadColumn(47)]
        public float Point44 { get; set; }


        [ColumnName("Point45"), LoadColumn(48)]
        public float Point45 { get; set; }


        [ColumnName("Point46"), LoadColumn(49)]
        public float Point46 { get; set; }


        [ColumnName("Point47"), LoadColumn(50)]
        public float Point47 { get; set; }


        [ColumnName("Point48"), LoadColumn(51)]
        public float Point48 { get; set; }


        [ColumnName("Point49"), LoadColumn(52)]
        public float Point49 { get; set; }


        [ColumnName("Point50"), LoadColumn(53)]
        public float Point50 { get; set; }


        [ColumnName("Point51"), LoadColumn(54)]
        public float Point51 { get; set; }


        [ColumnName("Point52"), LoadColumn(55)]
        public float Point52 { get; set; }


        [ColumnName("Point53"), LoadColumn(56)]
        public float Point53 { get; set; }


        [ColumnName("Point54"), LoadColumn(57)]
        public float Point54 { get; set; }


        [ColumnName("Point55"), LoadColumn(58)]
        public float Point55 { get; set; }


        [ColumnName("Point56"), LoadColumn(59)]
        public float Point56 { get; set; }


        [ColumnName("Point57"), LoadColumn(60)]
        public float Point57 { get; set; }


        [ColumnName("Point58"), LoadColumn(61)]
        public float Point58 { get; set; }


        [ColumnName("Point59"), LoadColumn(62)]
        public float Point59 { get; set; }


        [ColumnName("Point60"), LoadColumn(63)]
        public float Point60 { get; set; }


        [ColumnName("Point61"), LoadColumn(64)]
        public float Point61 { get; set; }


        [ColumnName("Point62"), LoadColumn(65)]
        public float Point62 { get; set; }


        [ColumnName("Point63"), LoadColumn(66)]
        public float Point63 { get; set; }


        [ColumnName("Point64"), LoadColumn(67)]
        public float Point64 { get; set; }


        [ColumnName("Point65"), LoadColumn(68)]
        public float Point65 { get; set; }


        [ColumnName("Point66"), LoadColumn(69)]
        public float Point66 { get; set; }


        [ColumnName("Point67"), LoadColumn(70)]
        public float Point67 { get; set; }


        [ColumnName("Point68"), LoadColumn(71)]
        public float Point68 { get; set; }


        [ColumnName("Point69"), LoadColumn(72)]
        public float Point69 { get; set; }


        [ColumnName("Point70"), LoadColumn(73)]
        public float Point70 { get; set; }


        [ColumnName("Point71"), LoadColumn(74)]
        public float Point71 { get; set; }


        [ColumnName("Point72"), LoadColumn(75)]
        public float Point72 { get; set; }


        [ColumnName("Point73"), LoadColumn(76)]
        public float Point73 { get; set; }


        [ColumnName("Point74"), LoadColumn(77)]
        public float Point74 { get; set; }


        [ColumnName("Point75"), LoadColumn(78)]
        public float Point75 { get; set; }


        [ColumnName("Point76"), LoadColumn(79)]
        public float Point76 { get; set; }


        [ColumnName("Point77"), LoadColumn(80)]
        public float Point77 { get; set; }


        [ColumnName("Point78"), LoadColumn(81)]
        public float Point78 { get; set; }


        [ColumnName("Point79"), LoadColumn(82)]
        public float Point79 { get; set; }


        [ColumnName("Point80"), LoadColumn(83)]
        public float Point80 { get; set; }


        [ColumnName("Point81"), LoadColumn(84)]
        public float Point81 { get; set; }


        [ColumnName("Point82"), LoadColumn(85)]
        public float Point82 { get; set; }


        [ColumnName("Point83"), LoadColumn(86)]
        public float Point83 { get; set; }


        [ColumnName("Point84"), LoadColumn(87)]
        public float Point84 { get; set; }


        [ColumnName("Point85"), LoadColumn(88)]
        public float Point85 { get; set; }


        [ColumnName("Point86"), LoadColumn(89)]
        public float Point86 { get; set; }


        [ColumnName("Point87"), LoadColumn(90)]
        public float Point87 { get; set; }


        [ColumnName("Point88"), LoadColumn(91)]
        public float Point88 { get; set; }


        [ColumnName("Point89"), LoadColumn(92)]
        public float Point89 { get; set; }


        [ColumnName("Point90"), LoadColumn(93)]
        public float Point90 { get; set; }


        [ColumnName("Point91"), LoadColumn(94)]
        public float Point91 { get; set; }


        [ColumnName("Point92"), LoadColumn(95)]
        public float Point92 { get; set; }


        [ColumnName("Point93"), LoadColumn(96)]
        public float Point93 { get; set; }


        [ColumnName("Point94"), LoadColumn(97)]
        public float Point94 { get; set; }


        [ColumnName("Point95"), LoadColumn(98)]
        public float Point95 { get; set; }


        [ColumnName("Point96"), LoadColumn(99)]
        public float Point96 { get; set; }


        [ColumnName("Point97"), LoadColumn(100)]
        public float Point97 { get; set; }


        [ColumnName("Point98"), LoadColumn(101)]
        public float Point98 { get; set; }


        [ColumnName("Point99"), LoadColumn(102)]
        public float Point99 { get; set; }


        [ColumnName("Point100"), LoadColumn(103)]
        public float Point100 { get; set; }


        [ColumnName("Point101"), LoadColumn(104)]
        public float Point101 { get; set; }


        [ColumnName("Point102"), LoadColumn(105)]
        public float Point102 { get; set; }


        [ColumnName("Point103"), LoadColumn(106)]
        public float Point103 { get; set; }


        [ColumnName("Point104"), LoadColumn(107)]
        public float Point104 { get; set; }


        [ColumnName("Point105"), LoadColumn(108)]
        public float Point105 { get; set; }


        [ColumnName("Point106"), LoadColumn(109)]
        public float Point106 { get; set; }


        [ColumnName("Point107"), LoadColumn(110)]
        public float Point107 { get; set; }


        [ColumnName("Point108"), LoadColumn(111)]
        public float Point108 { get; set; }


        [ColumnName("Point109"), LoadColumn(112)]
        public float Point109 { get; set; }


        [ColumnName("Point110"), LoadColumn(113)]
        public float Point110 { get; set; }


        [ColumnName("Point111"), LoadColumn(114)]
        public float Point111 { get; set; }


        [ColumnName("Point112"), LoadColumn(115)]
        public float Point112 { get; set; }


        [ColumnName("Point113"), LoadColumn(116)]
        public float Point113 { get; set; }


        [ColumnName("Point114"), LoadColumn(117)]
        public float Point114 { get; set; }


        [ColumnName("Point115"), LoadColumn(118)]
        public float Point115 { get; set; }


        [ColumnName("Point116"), LoadColumn(119)]
        public float Point116 { get; set; }


        [ColumnName("Point117"), LoadColumn(120)]
        public float Point117 { get; set; }


        [ColumnName("Point118"), LoadColumn(121)]
        public float Point118 { get; set; }


        [ColumnName("Point119"), LoadColumn(122)]
        public float Point119 { get; set; }


        [ColumnName("Point120"), LoadColumn(123)]
        public float Point120 { get; set; }


        [ColumnName("Point121"), LoadColumn(124)]
        public float Point121 { get; set; }


        [ColumnName("Point122"), LoadColumn(125)]
        public float Point122 { get; set; }


        [ColumnName("Point123"), LoadColumn(126)]
        public float Point123 { get; set; }


        [ColumnName("Point124"), LoadColumn(127)]
        public float Point124 { get; set; }


        [ColumnName("Point125"), LoadColumn(128)]
        public float Point125 { get; set; }


        [ColumnName("Point126"), LoadColumn(129)]
        public float Point126 { get; set; }


        [ColumnName("Point127"), LoadColumn(130)]
        public float Point127 { get; set; }


        [ColumnName("Point128"), LoadColumn(131)]
        public float Point128 { get; set; }


        [ColumnName("Point129"), LoadColumn(132)]
        public float Point129 { get; set; }


        [ColumnName("Point130"), LoadColumn(133)]
        public float Point130 { get; set; }


        [ColumnName("Point131"), LoadColumn(134)]
        public float Point131 { get; set; }


        [ColumnName("Point132"), LoadColumn(135)]
        public float Point132 { get; set; }


        [ColumnName("Point133"), LoadColumn(136)]
        public float Point133 { get; set; }


        [ColumnName("Point134"), LoadColumn(137)]
        public float Point134 { get; set; }


        [ColumnName("Point135"), LoadColumn(138)]
        public float Point135 { get; set; }


        [ColumnName("Point136"), LoadColumn(139)]
        public float Point136 { get; set; }


        [ColumnName("Point137"), LoadColumn(140)]
        public float Point137 { get; set; }


        [ColumnName("Point138"), LoadColumn(141)]
        public float Point138 { get; set; }


        [ColumnName("Point139"), LoadColumn(142)]
        public float Point139 { get; set; }


        [ColumnName("Point140"), LoadColumn(143)]
        public float Point140 { get; set; }


        [ColumnName("Point141"), LoadColumn(144)]
        public float Point141 { get; set; }


        [ColumnName("Point142"), LoadColumn(145)]
        public float Point142 { get; set; }


        [ColumnName("Point143"), LoadColumn(146)]
        public float Point143 { get; set; }


        [ColumnName("Point144"), LoadColumn(147)]
        public float Point144 { get; set; }


        [ColumnName("Point145"), LoadColumn(148)]
        public float Point145 { get; set; }


        [ColumnName("Point146"), LoadColumn(149)]
        public float Point146 { get; set; }


        [ColumnName("Point147"), LoadColumn(150)]
        public float Point147 { get; set; }


        [ColumnName("Point148"), LoadColumn(151)]
        public float Point148 { get; set; }


        [ColumnName("Point149"), LoadColumn(152)]
        public float Point149 { get; set; }


        [ColumnName("Point150"), LoadColumn(153)]
        public float Point150 { get; set; }


        [ColumnName("Point151"), LoadColumn(154)]
        public float Point151 { get; set; }


        [ColumnName("Point152"), LoadColumn(155)]
        public float Point152 { get; set; }


        [ColumnName("Point153"), LoadColumn(156)]
        public float Point153 { get; set; }


        [ColumnName("Point154"), LoadColumn(157)]
        public float Point154 { get; set; }


        [ColumnName("Point155"), LoadColumn(158)]
        public float Point155 { get; set; }


        [ColumnName("Point156"), LoadColumn(159)]
        public float Point156 { get; set; }


        [ColumnName("Point157"), LoadColumn(160)]
        public float Point157 { get; set; }


        [ColumnName("Point158"), LoadColumn(161)]
        public float Point158 { get; set; }


        [ColumnName("Point159"), LoadColumn(162)]
        public float Point159 { get; set; }


        [ColumnName("Point160"), LoadColumn(163)]
        public float Point160 { get; set; }


        [ColumnName("Point161"), LoadColumn(164)]
        public float Point161 { get; set; }


        [ColumnName("Point162"), LoadColumn(165)]
        public float Point162 { get; set; }


        [ColumnName("Point163"), LoadColumn(166)]
        public float Point163 { get; set; }


        [ColumnName("Point164"), LoadColumn(167)]
        public float Point164 { get; set; }


        [ColumnName("Point165"), LoadColumn(168)]
        public float Point165 { get; set; }


        [ColumnName("Point166"), LoadColumn(169)]
        public float Point166 { get; set; }


        [ColumnName("Point167"), LoadColumn(170)]
        public float Point167 { get; set; }


        [ColumnName("Point168"), LoadColumn(171)]
        public float Point168 { get; set; }


        [ColumnName("Point169"), LoadColumn(172)]
        public float Point169 { get; set; }


        [ColumnName("Point170"), LoadColumn(173)]
        public float Point170 { get; set; }


        [ColumnName("Point171"), LoadColumn(174)]
        public float Point171 { get; set; }


        [ColumnName("Point172"), LoadColumn(175)]
        public float Point172 { get; set; }


        [ColumnName("Point173"), LoadColumn(176)]
        public float Point173 { get; set; }


        [ColumnName("Point174"), LoadColumn(177)]
        public float Point174 { get; set; }


        [ColumnName("Point175"), LoadColumn(178)]
        public float Point175 { get; set; }


        [ColumnName("Point176"), LoadColumn(179)]
        public float Point176 { get; set; }


        [ColumnName("Point177"), LoadColumn(180)]
        public float Point177 { get; set; }


        [ColumnName("Point178"), LoadColumn(181)]
        public float Point178 { get; set; }


        [ColumnName("Point179"), LoadColumn(182)]
        public float Point179 { get; set; }


        [ColumnName("Point180"), LoadColumn(183)]
        public float Point180 { get; set; }


        [ColumnName("Point181"), LoadColumn(184)]
        public float Point181 { get; set; }


        [ColumnName("Point182"), LoadColumn(185)]
        public float Point182 { get; set; }


        [ColumnName("Point183"), LoadColumn(186)]
        public float Point183 { get; set; }


        [ColumnName("Point184"), LoadColumn(187)]
        public float Point184 { get; set; }


        [ColumnName("Point185"), LoadColumn(188)]
        public float Point185 { get; set; }


        [ColumnName("Point186"), LoadColumn(189)]
        public float Point186 { get; set; }


        [ColumnName("Point187"), LoadColumn(190)]
        public float Point187 { get; set; }


        [ColumnName("Point188"), LoadColumn(191)]
        public float Point188 { get; set; }


        [ColumnName("Point189"), LoadColumn(192)]
        public float Point189 { get; set; }


        [ColumnName("Point190"), LoadColumn(193)]
        public float Point190 { get; set; }


        [ColumnName("Point191"), LoadColumn(194)]
        public float Point191 { get; set; }


        [ColumnName("Point192"), LoadColumn(195)]
        public float Point192 { get; set; }


        [ColumnName("Point193"), LoadColumn(196)]
        public float Point193 { get; set; }


        [ColumnName("Point194"), LoadColumn(197)]
        public float Point194 { get; set; }


        [ColumnName("Point195"), LoadColumn(198)]
        public float Point195 { get; set; }


        [ColumnName("Point196"), LoadColumn(199)]
        public float Point196 { get; set; }


        [ColumnName("Point197"), LoadColumn(200)]
        public float Point197 { get; set; }


        [ColumnName("Point198"), LoadColumn(201)]
        public float Point198 { get; set; }


        [ColumnName("Point199"), LoadColumn(202)]
        public float Point199 { get; set; }


        [ColumnName("Point200"), LoadColumn(203)]
        public float Point200 { get; set; }


        [ColumnName("Point201"), LoadColumn(204)]
        public float Point201 { get; set; }


        [ColumnName("Point202"), LoadColumn(205)]
        public float Point202 { get; set; }


        [ColumnName("Point203"), LoadColumn(206)]
        public float Point203 { get; set; }


        [ColumnName("Point204"), LoadColumn(207)]
        public float Point204 { get; set; }


        [ColumnName("Point205"), LoadColumn(208)]
        public float Point205 { get; set; }


        [ColumnName("Point206"), LoadColumn(209)]
        public float Point206 { get; set; }


        [ColumnName("Point207"), LoadColumn(210)]
        public float Point207 { get; set; }


        [ColumnName("Point208"), LoadColumn(211)]
        public float Point208 { get; set; }


        [ColumnName("Point209"), LoadColumn(212)]
        public float Point209 { get; set; }


        [ColumnName("Point210"), LoadColumn(213)]
        public float Point210 { get; set; }


        [ColumnName("Point211"), LoadColumn(214)]
        public float Point211 { get; set; }


        [ColumnName("Point212"), LoadColumn(215)]
        public float Point212 { get; set; }


        [ColumnName("Point213"), LoadColumn(216)]
        public float Point213 { get; set; }


        [ColumnName("Point214"), LoadColumn(217)]
        public float Point214 { get; set; }


        [ColumnName("Point215"), LoadColumn(218)]
        public float Point215 { get; set; }


        [ColumnName("Point216"), LoadColumn(219)]
        public float Point216 { get; set; }


        [ColumnName("Point217"), LoadColumn(220)]
        public float Point217 { get; set; }


        [ColumnName("Point218"), LoadColumn(221)]
        public float Point218 { get; set; }


        [ColumnName("Point219"), LoadColumn(222)]
        public float Point219 { get; set; }


        [ColumnName("Point220"), LoadColumn(223)]
        public float Point220 { get; set; }


        [ColumnName("Point221"), LoadColumn(224)]
        public float Point221 { get; set; }


        [ColumnName("Point222"), LoadColumn(225)]
        public float Point222 { get; set; }


        [ColumnName("Point223"), LoadColumn(226)]
        public float Point223 { get; set; }


        [ColumnName("Point224"), LoadColumn(227)]
        public float Point224 { get; set; }


        [ColumnName("Point225"), LoadColumn(228)]
        public float Point225 { get; set; }


        [ColumnName("IsBlack"), LoadColumn(229)]
        public bool IsBlack { get; set; }


        [ColumnName("X"), LoadColumn(230)]
        public float X { get; set; }


        [ColumnName("Y"), LoadColumn(231)]
        public float Y { get; set; }


        [ColumnName("IsWin"), LoadColumn(232)]
        public bool IsWin { get; set; }

        public void SetPoint(int[,] points)
        {
            Type entityType = this.GetType();

            for (int i = 0; i < 15; i++)
            {
                for (int j = 0; j < 15; j++)
                {
                    int number = i * 15 + j + 1;

                    PropertyInfo propertyInfo = entityType.GetProperty($"Point{number}");

                    propertyInfo.SetValue(this, points[i, j]);
                }
            }
        }
    }
}
