// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace Zzb_ML_GobangML.Model
{
    public class ModelInput
    {

        [ColumnName("Map"), LoadColumn(4)]
        public string Map { get; set; }


        [ColumnName("IsBlack"), LoadColumn(5)]
        public bool IsBlack { get; set; }


        [ColumnName("Target"), LoadColumn(6)]
        public float Target { get; set; }


        [ColumnName("IsWin"), LoadColumn(7)]
        public bool IsWin { get; set; }


    }
}
