// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zzb.ML.EF;

namespace Zzb.ML.EF.Migrations
{
    [DbContext(typeof(ZzbContext))]
    [Migration("20200928044355_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zzb.ML.EF.Gobang", b =>
                {
                    b.Property<Guid>("GobangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBlack")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWin")
                        .HasColumnType("bit");

                    b.Property<int>("Point1")
                        .HasColumnType("int");

                    b.Property<int>("Point10")
                        .HasColumnType("int");

                    b.Property<int>("Point100")
                        .HasColumnType("int");

                    b.Property<int>("Point101")
                        .HasColumnType("int");

                    b.Property<int>("Point102")
                        .HasColumnType("int");

                    b.Property<int>("Point103")
                        .HasColumnType("int");

                    b.Property<int>("Point104")
                        .HasColumnType("int");

                    b.Property<int>("Point105")
                        .HasColumnType("int");

                    b.Property<int>("Point106")
                        .HasColumnType("int");

                    b.Property<int>("Point107")
                        .HasColumnType("int");

                    b.Property<int>("Point108")
                        .HasColumnType("int");

                    b.Property<int>("Point109")
                        .HasColumnType("int");

                    b.Property<int>("Point11")
                        .HasColumnType("int");

                    b.Property<int>("Point110")
                        .HasColumnType("int");

                    b.Property<int>("Point111")
                        .HasColumnType("int");

                    b.Property<int>("Point112")
                        .HasColumnType("int");

                    b.Property<int>("Point113")
                        .HasColumnType("int");

                    b.Property<int>("Point114")
                        .HasColumnType("int");

                    b.Property<int>("Point115")
                        .HasColumnType("int");

                    b.Property<int>("Point116")
                        .HasColumnType("int");

                    b.Property<int>("Point117")
                        .HasColumnType("int");

                    b.Property<int>("Point118")
                        .HasColumnType("int");

                    b.Property<int>("Point119")
                        .HasColumnType("int");

                    b.Property<int>("Point12")
                        .HasColumnType("int");

                    b.Property<int>("Point120")
                        .HasColumnType("int");

                    b.Property<int>("Point121")
                        .HasColumnType("int");

                    b.Property<int>("Point122")
                        .HasColumnType("int");

                    b.Property<int>("Point123")
                        .HasColumnType("int");

                    b.Property<int>("Point124")
                        .HasColumnType("int");

                    b.Property<int>("Point125")
                        .HasColumnType("int");

                    b.Property<int>("Point126")
                        .HasColumnType("int");

                    b.Property<int>("Point127")
                        .HasColumnType("int");

                    b.Property<int>("Point128")
                        .HasColumnType("int");

                    b.Property<int>("Point129")
                        .HasColumnType("int");

                    b.Property<int>("Point13")
                        .HasColumnType("int");

                    b.Property<int>("Point130")
                        .HasColumnType("int");

                    b.Property<int>("Point131")
                        .HasColumnType("int");

                    b.Property<int>("Point132")
                        .HasColumnType("int");

                    b.Property<int>("Point133")
                        .HasColumnType("int");

                    b.Property<int>("Point134")
                        .HasColumnType("int");

                    b.Property<int>("Point135")
                        .HasColumnType("int");

                    b.Property<int>("Point136")
                        .HasColumnType("int");

                    b.Property<int>("Point137")
                        .HasColumnType("int");

                    b.Property<int>("Point138")
                        .HasColumnType("int");

                    b.Property<int>("Point139")
                        .HasColumnType("int");

                    b.Property<int>("Point14")
                        .HasColumnType("int");

                    b.Property<int>("Point140")
                        .HasColumnType("int");

                    b.Property<int>("Point141")
                        .HasColumnType("int");

                    b.Property<int>("Point142")
                        .HasColumnType("int");

                    b.Property<int>("Point143")
                        .HasColumnType("int");

                    b.Property<int>("Point144")
                        .HasColumnType("int");

                    b.Property<int>("Point145")
                        .HasColumnType("int");

                    b.Property<int>("Point146")
                        .HasColumnType("int");

                    b.Property<int>("Point147")
                        .HasColumnType("int");

                    b.Property<int>("Point148")
                        .HasColumnType("int");

                    b.Property<int>("Point149")
                        .HasColumnType("int");

                    b.Property<int>("Point15")
                        .HasColumnType("int");

                    b.Property<int>("Point150")
                        .HasColumnType("int");

                    b.Property<int>("Point151")
                        .HasColumnType("int");

                    b.Property<int>("Point152")
                        .HasColumnType("int");

                    b.Property<int>("Point153")
                        .HasColumnType("int");

                    b.Property<int>("Point154")
                        .HasColumnType("int");

                    b.Property<int>("Point155")
                        .HasColumnType("int");

                    b.Property<int>("Point156")
                        .HasColumnType("int");

                    b.Property<int>("Point157")
                        .HasColumnType("int");

                    b.Property<int>("Point158")
                        .HasColumnType("int");

                    b.Property<int>("Point159")
                        .HasColumnType("int");

                    b.Property<int>("Point16")
                        .HasColumnType("int");

                    b.Property<int>("Point160")
                        .HasColumnType("int");

                    b.Property<int>("Point161")
                        .HasColumnType("int");

                    b.Property<int>("Point162")
                        .HasColumnType("int");

                    b.Property<int>("Point163")
                        .HasColumnType("int");

                    b.Property<int>("Point164")
                        .HasColumnType("int");

                    b.Property<int>("Point165")
                        .HasColumnType("int");

                    b.Property<int>("Point166")
                        .HasColumnType("int");

                    b.Property<int>("Point167")
                        .HasColumnType("int");

                    b.Property<int>("Point168")
                        .HasColumnType("int");

                    b.Property<int>("Point169")
                        .HasColumnType("int");

                    b.Property<int>("Point17")
                        .HasColumnType("int");

                    b.Property<int>("Point170")
                        .HasColumnType("int");

                    b.Property<int>("Point171")
                        .HasColumnType("int");

                    b.Property<int>("Point172")
                        .HasColumnType("int");

                    b.Property<int>("Point173")
                        .HasColumnType("int");

                    b.Property<int>("Point174")
                        .HasColumnType("int");

                    b.Property<int>("Point175")
                        .HasColumnType("int");

                    b.Property<int>("Point176")
                        .HasColumnType("int");

                    b.Property<int>("Point177")
                        .HasColumnType("int");

                    b.Property<int>("Point178")
                        .HasColumnType("int");

                    b.Property<int>("Point179")
                        .HasColumnType("int");

                    b.Property<int>("Point18")
                        .HasColumnType("int");

                    b.Property<int>("Point180")
                        .HasColumnType("int");

                    b.Property<int>("Point181")
                        .HasColumnType("int");

                    b.Property<int>("Point182")
                        .HasColumnType("int");

                    b.Property<int>("Point183")
                        .HasColumnType("int");

                    b.Property<int>("Point184")
                        .HasColumnType("int");

                    b.Property<int>("Point185")
                        .HasColumnType("int");

                    b.Property<int>("Point186")
                        .HasColumnType("int");

                    b.Property<int>("Point187")
                        .HasColumnType("int");

                    b.Property<int>("Point188")
                        .HasColumnType("int");

                    b.Property<int>("Point189")
                        .HasColumnType("int");

                    b.Property<int>("Point19")
                        .HasColumnType("int");

                    b.Property<int>("Point190")
                        .HasColumnType("int");

                    b.Property<int>("Point191")
                        .HasColumnType("int");

                    b.Property<int>("Point192")
                        .HasColumnType("int");

                    b.Property<int>("Point193")
                        .HasColumnType("int");

                    b.Property<int>("Point194")
                        .HasColumnType("int");

                    b.Property<int>("Point195")
                        .HasColumnType("int");

                    b.Property<int>("Point196")
                        .HasColumnType("int");

                    b.Property<int>("Point197")
                        .HasColumnType("int");

                    b.Property<int>("Point198")
                        .HasColumnType("int");

                    b.Property<int>("Point199")
                        .HasColumnType("int");

                    b.Property<int>("Point2")
                        .HasColumnType("int");

                    b.Property<int>("Point20")
                        .HasColumnType("int");

                    b.Property<int>("Point200")
                        .HasColumnType("int");

                    b.Property<int>("Point201")
                        .HasColumnType("int");

                    b.Property<int>("Point202")
                        .HasColumnType("int");

                    b.Property<int>("Point203")
                        .HasColumnType("int");

                    b.Property<int>("Point204")
                        .HasColumnType("int");

                    b.Property<int>("Point205")
                        .HasColumnType("int");

                    b.Property<int>("Point206")
                        .HasColumnType("int");

                    b.Property<int>("Point207")
                        .HasColumnType("int");

                    b.Property<int>("Point208")
                        .HasColumnType("int");

                    b.Property<int>("Point209")
                        .HasColumnType("int");

                    b.Property<int>("Point21")
                        .HasColumnType("int");

                    b.Property<int>("Point210")
                        .HasColumnType("int");

                    b.Property<int>("Point211")
                        .HasColumnType("int");

                    b.Property<int>("Point212")
                        .HasColumnType("int");

                    b.Property<int>("Point213")
                        .HasColumnType("int");

                    b.Property<int>("Point214")
                        .HasColumnType("int");

                    b.Property<int>("Point215")
                        .HasColumnType("int");

                    b.Property<int>("Point216")
                        .HasColumnType("int");

                    b.Property<int>("Point217")
                        .HasColumnType("int");

                    b.Property<int>("Point218")
                        .HasColumnType("int");

                    b.Property<int>("Point219")
                        .HasColumnType("int");

                    b.Property<int>("Point22")
                        .HasColumnType("int");

                    b.Property<int>("Point220")
                        .HasColumnType("int");

                    b.Property<int>("Point221")
                        .HasColumnType("int");

                    b.Property<int>("Point222")
                        .HasColumnType("int");

                    b.Property<int>("Point223")
                        .HasColumnType("int");

                    b.Property<int>("Point224")
                        .HasColumnType("int");

                    b.Property<int>("Point225")
                        .HasColumnType("int");

                    b.Property<int>("Point23")
                        .HasColumnType("int");

                    b.Property<int>("Point24")
                        .HasColumnType("int");

                    b.Property<int>("Point25")
                        .HasColumnType("int");

                    b.Property<int>("Point26")
                        .HasColumnType("int");

                    b.Property<int>("Point27")
                        .HasColumnType("int");

                    b.Property<int>("Point28")
                        .HasColumnType("int");

                    b.Property<int>("Point29")
                        .HasColumnType("int");

                    b.Property<int>("Point3")
                        .HasColumnType("int");

                    b.Property<int>("Point30")
                        .HasColumnType("int");

                    b.Property<int>("Point31")
                        .HasColumnType("int");

                    b.Property<int>("Point32")
                        .HasColumnType("int");

                    b.Property<int>("Point33")
                        .HasColumnType("int");

                    b.Property<int>("Point34")
                        .HasColumnType("int");

                    b.Property<int>("Point35")
                        .HasColumnType("int");

                    b.Property<int>("Point36")
                        .HasColumnType("int");

                    b.Property<int>("Point37")
                        .HasColumnType("int");

                    b.Property<int>("Point38")
                        .HasColumnType("int");

                    b.Property<int>("Point39")
                        .HasColumnType("int");

                    b.Property<int>("Point4")
                        .HasColumnType("int");

                    b.Property<int>("Point40")
                        .HasColumnType("int");

                    b.Property<int>("Point41")
                        .HasColumnType("int");

                    b.Property<int>("Point42")
                        .HasColumnType("int");

                    b.Property<int>("Point43")
                        .HasColumnType("int");

                    b.Property<int>("Point44")
                        .HasColumnType("int");

                    b.Property<int>("Point45")
                        .HasColumnType("int");

                    b.Property<int>("Point46")
                        .HasColumnType("int");

                    b.Property<int>("Point47")
                        .HasColumnType("int");

                    b.Property<int>("Point48")
                        .HasColumnType("int");

                    b.Property<int>("Point49")
                        .HasColumnType("int");

                    b.Property<int>("Point5")
                        .HasColumnType("int");

                    b.Property<int>("Point50")
                        .HasColumnType("int");

                    b.Property<int>("Point51")
                        .HasColumnType("int");

                    b.Property<int>("Point52")
                        .HasColumnType("int");

                    b.Property<int>("Point53")
                        .HasColumnType("int");

                    b.Property<int>("Point54")
                        .HasColumnType("int");

                    b.Property<int>("Point55")
                        .HasColumnType("int");

                    b.Property<int>("Point56")
                        .HasColumnType("int");

                    b.Property<int>("Point57")
                        .HasColumnType("int");

                    b.Property<int>("Point58")
                        .HasColumnType("int");

                    b.Property<int>("Point59")
                        .HasColumnType("int");

                    b.Property<int>("Point6")
                        .HasColumnType("int");

                    b.Property<int>("Point60")
                        .HasColumnType("int");

                    b.Property<int>("Point61")
                        .HasColumnType("int");

                    b.Property<int>("Point62")
                        .HasColumnType("int");

                    b.Property<int>("Point63")
                        .HasColumnType("int");

                    b.Property<int>("Point64")
                        .HasColumnType("int");

                    b.Property<int>("Point65")
                        .HasColumnType("int");

                    b.Property<int>("Point66")
                        .HasColumnType("int");

                    b.Property<int>("Point67")
                        .HasColumnType("int");

                    b.Property<int>("Point68")
                        .HasColumnType("int");

                    b.Property<int>("Point69")
                        .HasColumnType("int");

                    b.Property<int>("Point7")
                        .HasColumnType("int");

                    b.Property<int>("Point70")
                        .HasColumnType("int");

                    b.Property<int>("Point71")
                        .HasColumnType("int");

                    b.Property<int>("Point72")
                        .HasColumnType("int");

                    b.Property<int>("Point73")
                        .HasColumnType("int");

                    b.Property<int>("Point74")
                        .HasColumnType("int");

                    b.Property<int>("Point75")
                        .HasColumnType("int");

                    b.Property<int>("Point76")
                        .HasColumnType("int");

                    b.Property<int>("Point77")
                        .HasColumnType("int");

                    b.Property<int>("Point78")
                        .HasColumnType("int");

                    b.Property<int>("Point79")
                        .HasColumnType("int");

                    b.Property<int>("Point8")
                        .HasColumnType("int");

                    b.Property<int>("Point80")
                        .HasColumnType("int");

                    b.Property<int>("Point81")
                        .HasColumnType("int");

                    b.Property<int>("Point82")
                        .HasColumnType("int");

                    b.Property<int>("Point83")
                        .HasColumnType("int");

                    b.Property<int>("Point84")
                        .HasColumnType("int");

                    b.Property<int>("Point85")
                        .HasColumnType("int");

                    b.Property<int>("Point86")
                        .HasColumnType("int");

                    b.Property<int>("Point87")
                        .HasColumnType("int");

                    b.Property<int>("Point88")
                        .HasColumnType("int");

                    b.Property<int>("Point89")
                        .HasColumnType("int");

                    b.Property<int>("Point9")
                        .HasColumnType("int");

                    b.Property<int>("Point90")
                        .HasColumnType("int");

                    b.Property<int>("Point91")
                        .HasColumnType("int");

                    b.Property<int>("Point92")
                        .HasColumnType("int");

                    b.Property<int>("Point93")
                        .HasColumnType("int");

                    b.Property<int>("Point94")
                        .HasColumnType("int");

                    b.Property<int>("Point95")
                        .HasColumnType("int");

                    b.Property<int>("Point96")
                        .HasColumnType("int");

                    b.Property<int>("Point97")
                        .HasColumnType("int");

                    b.Property<int>("Point98")
                        .HasColumnType("int");

                    b.Property<int>("Point99")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("GobangId");

                    b.ToTable("Gobangs");
                });
#pragma warning restore 612, 618
        }
    }
}
