// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zzb.ML.EF;

namespace Zzb.ML.EF.Migrations
{
    [DbContext(typeof(ZzbContext))]
    [Migration("20200928070211_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zzb.ML.EF.Gobang", b =>
                {
                    b.Property<Guid>("GobangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBlack")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWin")
                        .HasColumnType("bit");

                    b.Property<float>("Point1")
                        .HasColumnType("real");

                    b.Property<float>("Point10")
                        .HasColumnType("real");

                    b.Property<float>("Point100")
                        .HasColumnType("real");

                    b.Property<float>("Point101")
                        .HasColumnType("real");

                    b.Property<float>("Point102")
                        .HasColumnType("real");

                    b.Property<float>("Point103")
                        .HasColumnType("real");

                    b.Property<float>("Point104")
                        .HasColumnType("real");

                    b.Property<float>("Point105")
                        .HasColumnType("real");

                    b.Property<float>("Point106")
                        .HasColumnType("real");

                    b.Property<float>("Point107")
                        .HasColumnType("real");

                    b.Property<float>("Point108")
                        .HasColumnType("real");

                    b.Property<float>("Point109")
                        .HasColumnType("real");

                    b.Property<float>("Point11")
                        .HasColumnType("real");

                    b.Property<float>("Point110")
                        .HasColumnType("real");

                    b.Property<float>("Point111")
                        .HasColumnType("real");

                    b.Property<float>("Point112")
                        .HasColumnType("real");

                    b.Property<float>("Point113")
                        .HasColumnType("real");

                    b.Property<float>("Point114")
                        .HasColumnType("real");

                    b.Property<float>("Point115")
                        .HasColumnType("real");

                    b.Property<float>("Point116")
                        .HasColumnType("real");

                    b.Property<float>("Point117")
                        .HasColumnType("real");

                    b.Property<float>("Point118")
                        .HasColumnType("real");

                    b.Property<float>("Point119")
                        .HasColumnType("real");

                    b.Property<float>("Point12")
                        .HasColumnType("real");

                    b.Property<float>("Point120")
                        .HasColumnType("real");

                    b.Property<float>("Point121")
                        .HasColumnType("real");

                    b.Property<float>("Point122")
                        .HasColumnType("real");

                    b.Property<float>("Point123")
                        .HasColumnType("real");

                    b.Property<float>("Point124")
                        .HasColumnType("real");

                    b.Property<float>("Point125")
                        .HasColumnType("real");

                    b.Property<float>("Point126")
                        .HasColumnType("real");

                    b.Property<float>("Point127")
                        .HasColumnType("real");

                    b.Property<float>("Point128")
                        .HasColumnType("real");

                    b.Property<float>("Point129")
                        .HasColumnType("real");

                    b.Property<float>("Point13")
                        .HasColumnType("real");

                    b.Property<float>("Point130")
                        .HasColumnType("real");

                    b.Property<float>("Point131")
                        .HasColumnType("real");

                    b.Property<float>("Point132")
                        .HasColumnType("real");

                    b.Property<float>("Point133")
                        .HasColumnType("real");

                    b.Property<float>("Point134")
                        .HasColumnType("real");

                    b.Property<float>("Point135")
                        .HasColumnType("real");

                    b.Property<float>("Point136")
                        .HasColumnType("real");

                    b.Property<float>("Point137")
                        .HasColumnType("real");

                    b.Property<float>("Point138")
                        .HasColumnType("real");

                    b.Property<float>("Point139")
                        .HasColumnType("real");

                    b.Property<float>("Point14")
                        .HasColumnType("real");

                    b.Property<float>("Point140")
                        .HasColumnType("real");

                    b.Property<float>("Point141")
                        .HasColumnType("real");

                    b.Property<float>("Point142")
                        .HasColumnType("real");

                    b.Property<float>("Point143")
                        .HasColumnType("real");

                    b.Property<float>("Point144")
                        .HasColumnType("real");

                    b.Property<float>("Point145")
                        .HasColumnType("real");

                    b.Property<float>("Point146")
                        .HasColumnType("real");

                    b.Property<float>("Point147")
                        .HasColumnType("real");

                    b.Property<float>("Point148")
                        .HasColumnType("real");

                    b.Property<float>("Point149")
                        .HasColumnType("real");

                    b.Property<float>("Point15")
                        .HasColumnType("real");

                    b.Property<float>("Point150")
                        .HasColumnType("real");

                    b.Property<float>("Point151")
                        .HasColumnType("real");

                    b.Property<float>("Point152")
                        .HasColumnType("real");

                    b.Property<float>("Point153")
                        .HasColumnType("real");

                    b.Property<float>("Point154")
                        .HasColumnType("real");

                    b.Property<float>("Point155")
                        .HasColumnType("real");

                    b.Property<float>("Point156")
                        .HasColumnType("real");

                    b.Property<float>("Point157")
                        .HasColumnType("real");

                    b.Property<float>("Point158")
                        .HasColumnType("real");

                    b.Property<float>("Point159")
                        .HasColumnType("real");

                    b.Property<float>("Point16")
                        .HasColumnType("real");

                    b.Property<float>("Point160")
                        .HasColumnType("real");

                    b.Property<float>("Point161")
                        .HasColumnType("real");

                    b.Property<float>("Point162")
                        .HasColumnType("real");

                    b.Property<float>("Point163")
                        .HasColumnType("real");

                    b.Property<float>("Point164")
                        .HasColumnType("real");

                    b.Property<float>("Point165")
                        .HasColumnType("real");

                    b.Property<float>("Point166")
                        .HasColumnType("real");

                    b.Property<float>("Point167")
                        .HasColumnType("real");

                    b.Property<float>("Point168")
                        .HasColumnType("real");

                    b.Property<float>("Point169")
                        .HasColumnType("real");

                    b.Property<float>("Point17")
                        .HasColumnType("real");

                    b.Property<float>("Point170")
                        .HasColumnType("real");

                    b.Property<float>("Point171")
                        .HasColumnType("real");

                    b.Property<float>("Point172")
                        .HasColumnType("real");

                    b.Property<float>("Point173")
                        .HasColumnType("real");

                    b.Property<float>("Point174")
                        .HasColumnType("real");

                    b.Property<float>("Point175")
                        .HasColumnType("real");

                    b.Property<float>("Point176")
                        .HasColumnType("real");

                    b.Property<float>("Point177")
                        .HasColumnType("real");

                    b.Property<float>("Point178")
                        .HasColumnType("real");

                    b.Property<float>("Point179")
                        .HasColumnType("real");

                    b.Property<float>("Point18")
                        .HasColumnType("real");

                    b.Property<float>("Point180")
                        .HasColumnType("real");

                    b.Property<float>("Point181")
                        .HasColumnType("real");

                    b.Property<float>("Point182")
                        .HasColumnType("real");

                    b.Property<float>("Point183")
                        .HasColumnType("real");

                    b.Property<float>("Point184")
                        .HasColumnType("real");

                    b.Property<float>("Point185")
                        .HasColumnType("real");

                    b.Property<float>("Point186")
                        .HasColumnType("real");

                    b.Property<float>("Point187")
                        .HasColumnType("real");

                    b.Property<float>("Point188")
                        .HasColumnType("real");

                    b.Property<float>("Point189")
                        .HasColumnType("real");

                    b.Property<float>("Point19")
                        .HasColumnType("real");

                    b.Property<float>("Point190")
                        .HasColumnType("real");

                    b.Property<float>("Point191")
                        .HasColumnType("real");

                    b.Property<float>("Point192")
                        .HasColumnType("real");

                    b.Property<float>("Point193")
                        .HasColumnType("real");

                    b.Property<float>("Point194")
                        .HasColumnType("real");

                    b.Property<float>("Point195")
                        .HasColumnType("real");

                    b.Property<float>("Point196")
                        .HasColumnType("real");

                    b.Property<float>("Point197")
                        .HasColumnType("real");

                    b.Property<float>("Point198")
                        .HasColumnType("real");

                    b.Property<float>("Point199")
                        .HasColumnType("real");

                    b.Property<float>("Point2")
                        .HasColumnType("real");

                    b.Property<float>("Point20")
                        .HasColumnType("real");

                    b.Property<float>("Point200")
                        .HasColumnType("real");

                    b.Property<float>("Point201")
                        .HasColumnType("real");

                    b.Property<float>("Point202")
                        .HasColumnType("real");

                    b.Property<float>("Point203")
                        .HasColumnType("real");

                    b.Property<float>("Point204")
                        .HasColumnType("real");

                    b.Property<float>("Point205")
                        .HasColumnType("real");

                    b.Property<float>("Point206")
                        .HasColumnType("real");

                    b.Property<float>("Point207")
                        .HasColumnType("real");

                    b.Property<float>("Point208")
                        .HasColumnType("real");

                    b.Property<float>("Point209")
                        .HasColumnType("real");

                    b.Property<float>("Point21")
                        .HasColumnType("real");

                    b.Property<float>("Point210")
                        .HasColumnType("real");

                    b.Property<float>("Point211")
                        .HasColumnType("real");

                    b.Property<float>("Point212")
                        .HasColumnType("real");

                    b.Property<float>("Point213")
                        .HasColumnType("real");

                    b.Property<float>("Point214")
                        .HasColumnType("real");

                    b.Property<float>("Point215")
                        .HasColumnType("real");

                    b.Property<float>("Point216")
                        .HasColumnType("real");

                    b.Property<float>("Point217")
                        .HasColumnType("real");

                    b.Property<float>("Point218")
                        .HasColumnType("real");

                    b.Property<float>("Point219")
                        .HasColumnType("real");

                    b.Property<float>("Point22")
                        .HasColumnType("real");

                    b.Property<float>("Point220")
                        .HasColumnType("real");

                    b.Property<float>("Point221")
                        .HasColumnType("real");

                    b.Property<float>("Point222")
                        .HasColumnType("real");

                    b.Property<float>("Point223")
                        .HasColumnType("real");

                    b.Property<float>("Point224")
                        .HasColumnType("real");

                    b.Property<float>("Point225")
                        .HasColumnType("real");

                    b.Property<float>("Point23")
                        .HasColumnType("real");

                    b.Property<float>("Point24")
                        .HasColumnType("real");

                    b.Property<float>("Point25")
                        .HasColumnType("real");

                    b.Property<float>("Point26")
                        .HasColumnType("real");

                    b.Property<float>("Point27")
                        .HasColumnType("real");

                    b.Property<float>("Point28")
                        .HasColumnType("real");

                    b.Property<float>("Point29")
                        .HasColumnType("real");

                    b.Property<float>("Point3")
                        .HasColumnType("real");

                    b.Property<float>("Point30")
                        .HasColumnType("real");

                    b.Property<float>("Point31")
                        .HasColumnType("real");

                    b.Property<float>("Point32")
                        .HasColumnType("real");

                    b.Property<float>("Point33")
                        .HasColumnType("real");

                    b.Property<float>("Point34")
                        .HasColumnType("real");

                    b.Property<float>("Point35")
                        .HasColumnType("real");

                    b.Property<float>("Point36")
                        .HasColumnType("real");

                    b.Property<float>("Point37")
                        .HasColumnType("real");

                    b.Property<float>("Point38")
                        .HasColumnType("real");

                    b.Property<float>("Point39")
                        .HasColumnType("real");

                    b.Property<float>("Point4")
                        .HasColumnType("real");

                    b.Property<float>("Point40")
                        .HasColumnType("real");

                    b.Property<float>("Point41")
                        .HasColumnType("real");

                    b.Property<float>("Point42")
                        .HasColumnType("real");

                    b.Property<float>("Point43")
                        .HasColumnType("real");

                    b.Property<float>("Point44")
                        .HasColumnType("real");

                    b.Property<float>("Point45")
                        .HasColumnType("real");

                    b.Property<float>("Point46")
                        .HasColumnType("real");

                    b.Property<float>("Point47")
                        .HasColumnType("real");

                    b.Property<float>("Point48")
                        .HasColumnType("real");

                    b.Property<float>("Point49")
                        .HasColumnType("real");

                    b.Property<float>("Point5")
                        .HasColumnType("real");

                    b.Property<float>("Point50")
                        .HasColumnType("real");

                    b.Property<float>("Point51")
                        .HasColumnType("real");

                    b.Property<float>("Point52")
                        .HasColumnType("real");

                    b.Property<float>("Point53")
                        .HasColumnType("real");

                    b.Property<float>("Point54")
                        .HasColumnType("real");

                    b.Property<float>("Point55")
                        .HasColumnType("real");

                    b.Property<float>("Point56")
                        .HasColumnType("real");

                    b.Property<float>("Point57")
                        .HasColumnType("real");

                    b.Property<float>("Point58")
                        .HasColumnType("real");

                    b.Property<float>("Point59")
                        .HasColumnType("real");

                    b.Property<float>("Point6")
                        .HasColumnType("real");

                    b.Property<float>("Point60")
                        .HasColumnType("real");

                    b.Property<float>("Point61")
                        .HasColumnType("real");

                    b.Property<float>("Point62")
                        .HasColumnType("real");

                    b.Property<float>("Point63")
                        .HasColumnType("real");

                    b.Property<float>("Point64")
                        .HasColumnType("real");

                    b.Property<float>("Point65")
                        .HasColumnType("real");

                    b.Property<float>("Point66")
                        .HasColumnType("real");

                    b.Property<float>("Point67")
                        .HasColumnType("real");

                    b.Property<float>("Point68")
                        .HasColumnType("real");

                    b.Property<float>("Point69")
                        .HasColumnType("real");

                    b.Property<float>("Point7")
                        .HasColumnType("real");

                    b.Property<float>("Point70")
                        .HasColumnType("real");

                    b.Property<float>("Point71")
                        .HasColumnType("real");

                    b.Property<float>("Point72")
                        .HasColumnType("real");

                    b.Property<float>("Point73")
                        .HasColumnType("real");

                    b.Property<float>("Point74")
                        .HasColumnType("real");

                    b.Property<float>("Point75")
                        .HasColumnType("real");

                    b.Property<float>("Point76")
                        .HasColumnType("real");

                    b.Property<float>("Point77")
                        .HasColumnType("real");

                    b.Property<float>("Point78")
                        .HasColumnType("real");

                    b.Property<float>("Point79")
                        .HasColumnType("real");

                    b.Property<float>("Point8")
                        .HasColumnType("real");

                    b.Property<float>("Point80")
                        .HasColumnType("real");

                    b.Property<float>("Point81")
                        .HasColumnType("real");

                    b.Property<float>("Point82")
                        .HasColumnType("real");

                    b.Property<float>("Point83")
                        .HasColumnType("real");

                    b.Property<float>("Point84")
                        .HasColumnType("real");

                    b.Property<float>("Point85")
                        .HasColumnType("real");

                    b.Property<float>("Point86")
                        .HasColumnType("real");

                    b.Property<float>("Point87")
                        .HasColumnType("real");

                    b.Property<float>("Point88")
                        .HasColumnType("real");

                    b.Property<float>("Point89")
                        .HasColumnType("real");

                    b.Property<float>("Point9")
                        .HasColumnType("real");

                    b.Property<float>("Point90")
                        .HasColumnType("real");

                    b.Property<float>("Point91")
                        .HasColumnType("real");

                    b.Property<float>("Point92")
                        .HasColumnType("real");

                    b.Property<float>("Point93")
                        .HasColumnType("real");

                    b.Property<float>("Point94")
                        .HasColumnType("real");

                    b.Property<float>("Point95")
                        .HasColumnType("real");

                    b.Property<float>("Point96")
                        .HasColumnType("real");

                    b.Property<float>("Point97")
                        .HasColumnType("real");

                    b.Property<float>("Point98")
                        .HasColumnType("real");

                    b.Property<float>("Point99")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("GobangId");

                    b.ToTable("Gobangs");
                });
#pragma warning restore 612, 618
        }
    }
}
