// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zzb.ML.EF;

namespace Zzb.ML.EF.Migrations
{
    [DbContext(typeof(ZzbContext))]
    [Migration("20201104033138_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zzb.ML.EF.MonteCarloTree", b =>
                {
                    b.Property<Guid>("MonteCarloTreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsBlack")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentTreeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("UCT")
                        .HasColumnType("float");

                    b.Property<long>("Win")
                        .HasColumnType("bigint");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("MonteCarloTreeId");

                    b.HasIndex("ParentTreeId");

                    b.ToTable("MonteCarloTrees");
                });

            modelBuilder.Entity("Zzb.ML.EF.MonteCarloTree", b =>
                {
                    b.HasOne("Zzb.ML.EF.MonteCarloTree", "ParentTree")
                        .WithMany("MonteCarloTrees")
                        .HasForeignKey("ParentTreeId");
                });
#pragma warning restore 612, 618
        }
    }
}
