// This file was auto-generated by ML.NET Model Builder. 

using System;
using Zzb_ML_GobangML.Model;

namespace Zzb_ML_GobangML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            ModelBuilder.CreateModel();
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Map = @"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
                IsBlack = true,
                Target = 89,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual IsWin with predicted IsWin from sample data...\n\n");
            Console.WriteLine($"Map: {sampleData.Map}");
            Console.WriteLine($"IsBlack: {sampleData.IsBlack}");
            Console.WriteLine($"Target: {sampleData.Target}");
            Console.WriteLine($"\n\nPredicted IsWin value {predictionResult.Prediction} \nPredicted IsWin scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
