// This file was auto-generated by ML.NET Model Builder. 

using System;
using Zzb_ML_GobangML.Model;

namespace Zzb_ML_GobangML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            ModelBuilder.CreateModel();
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Map = @"Map022000200000000002102000100000220010000100001021200000221010020001101000000010000200000000000000000010000100100001021020000100200100110000010020002120120000000000002002100000002000220010000000000000020120002000200000100102010",
                IsBlack = true,
                Target = 140,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual IsWin with predicted IsWin from sample data...\n\n");
            Console.WriteLine($"Map: {sampleData.Map}");
            Console.WriteLine($"IsBlack: {sampleData.IsBlack}");
            Console.WriteLine($"Target: {sampleData.Target}");
            Console.WriteLine($"\n\nPredicted IsWin value {predictionResult.Prediction} \nPredicted IsWin scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
